force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Phase__c/Project_Phase__c.object-meta.xml
<CustomObject>
    <label>Project Phase</label>
    <nameField>
        <label>Project Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Phase__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Phases</relationshipLabel>
    <relationshipName>Project_Phases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProjectPhaseTriggerHandler.cls
public class ProjectPhaseTriggerHandler extends TriggerHandler {
    public override void afterUpdate() {
        List<Project__c> projects = getProjectsAndPhases(
            pluckProjectIds((List<Project_Phase__c>) Trigger.new)
        );
        ProjectPhaseContiguousDateValidator validator = new ProjectPhaseContiguousDateValidator();
        validator.setRelatedData(projects);
        validator.validate((List<Project_Phase__c>) Trigger.new);
    }

    private Set<Id> pluckProjectIds(List<Project_Phase__c> projectPhases) {
        Set<Id> projectIds = new Set<Id>();
        for (Project_Phase__c projectPhase : projectPhases) {
            projectIds.add(projectPhase.Project__c);
        }
        return projectIds;
    }

    private List<Project__c> getProjectsAndPhases(Set<Id> projectIds) {
        List<Project__c> projects = [
            SELECT
                Name,
                (
                    SELECT Name, Start_Date__c, End_Date__c
                    FROM Project_Phases__r
                    ORDER BY Start_Date__c
                )
            FROM Project__c
            WHERE Id IN :projectIds
        ];
        return projects;
    }
}